name: carrota_flutter
description: Flutter Carrota / Lumo.
publish_to: "none"
version: 1.1.0+2
  
environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.9.1
  sqflite: ^2.4.3
  video_player: ^2.14.0
  share_plus: ^13.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/lettuce.mp4
    - assets/videos/apples.mp4
    - assets/videos/fresh_fruit.mp4
    - assets/videos/lemons.mp4
    - assets/videos/citrus.mp4
